name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Minute Hour Day Month Day
    - cron: 0 19 * * * # 19:00 UTC is 4:00 JST

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_LOC_CHART: "false" # To error due to bugs(https://github.com/anmol098/waka-readme-stats/issues/337)
          SHOW_OS: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_PROJECTS: "false"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_UPDATED_DATE: "true"
