name: Profile

on:
  workflow_dispatch:
  schedule:
    # Minute Hour Day Month Day
    - cron: 0 19 * * * # 19:00 UTC is 4:00 JST

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}