name: Profile

on:
  workflow_dispatch:
  schedule:
    # Minute Hour Day Month Day
    - cron: 0 19 * * * # 19:00 UTC is 4:00 JST

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # https://github.com/athul/waka-readme
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
